### PR TITLE
support for mailaddrmap lookups in table-mysql

### PR DESCRIPTION
**Pull request by fgma**
Similar to https://github.com/OpenSMTPD/OpenSMTPD-extras/pull/59:

Currently lookups for K_MAILADDRMAP won't work with table-mysql. This PR enhances table-mysql to support them using "query_mailaddrmap" inside the config file

@poolpOrg Do you plan a release together with opensmtpd 6.6?

### CODE REVIEW

**Comment by poolpOrg** [comment]
I'll tag a release yes

**Comment by fgma** [comment]
Perfect, thanks!

**Comment by poolpOrg** [comment]
This will be the last release hopefully, I hope I can pull a rewrite of the API used in filters/tables/schedulers before OpenSMTPD 6.7.0 that would make it work similarly to filters, allowing people to easily write addons with any language.

I won't kill OpenSMTPD-extras before the existing addons have been rewritten to the new interface, so there will not be additions to -extras, only bug fixes and minor commits like yours.

**Comment by fgma** [comment]
Is it planned to have official support for currently supported backends like mysql/postgres/etc? Which repository are you using for development? I'd like to follow development. Maybe I can provide some help implementing a backend.

**Pull request merged**
