### PR TITLE
Make spamd host/port configurable in filter-spamassassin

### PR DESCRIPTION
**Pull request by sarneaud**

### CODE REVIEW

**Comment by snimmagadda** [comment]
Hi, the author of spamassassin filter (who doesn't have a github account to comment here) has the following feedback on you pull request. Feel free to have a conversation on misc@opensmtpd.org for your modifications/diffs.

In general host and port are very rarely needed to be configured as even in
large setups spamassassin usually runs on the same machine.  However, if this
feature is really wanted, there are still several problems with this pull
request, which need to be fixed before merge:

1. the added prefix DEF_ makes no sense and does not match other style in other
   source files
2. static host and port should be initialized with the default #defines on top
   of file instead of main()
3. hints.ai_flags should be completely removed to allow specification of ports
   as service name as well
4. the port getopt might also contain leading whitespace which should be
   skipped similar to the host
5. this diff was obviously not tested as it will not work: the filter runs in a
   chroot() which does not contain a /etc/resolv.conf, so getaddrinfo() will fail
     -> so add another option -c for chroot path or disabled chroot and use
        this to allow user to specify chroot -- if chroot is not given add
        filter_api_no_chroot()

**Comment by poolpOrg** [comment]
@sarneaud are you still working on this and has this evolved ?

the current pull request will not apply due to conflicts, are you going to update the diff, give up or submit a new pull request later ?

in other words, should this still be open ? :-)

**Comment by sarneaud** [comment]
Sorry, I'm still interested in working on this, but things have been a bit critical in my day job the past couple of weeks.

If it's what you prefer for review queue housekeeping, I can close this and open a new PR later.

**Comment by sarneaud** [comment]
Hi, I've upgraded to the newest version of OpenSMTPD et al and it's solved a bunch of the problems I was having.  I won't be working on the code until I've experimented more with the latest version, so I'll close this PR.

**Pull request closed without merging**
